// Code generated by sqlc. DO NOT EDIT.
// source: chair.sql

package mysql

import (
	"context"
)

const countChairWithPriceCondition = `-- name: CountChairWithPriceCondition :one
SELECT COUNT(*) FROM chair WHERE price >= ? AND price < ?
`

type CountChairWithPriceConditionParams struct {
	Price   int32
	Price_2 int32
}

func (q *Queries) CountChairWithPriceCondition(ctx context.Context, arg CountChairWithPriceConditionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChairWithPriceCondition, arg.Price, arg.Price_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChair = `-- name: CreateChair :exec
INSERT INTO chair(id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateChairParams struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Price       int32
	Height      int32
	Width       int32
	Depth       int32
	Color       string
	Features    string
	Kind        string
	Popularity  int32
	Stock       int32
}

func (q *Queries) CreateChair(ctx context.Context, arg CreateChairParams) error {
	_, err := q.db.ExecContext(ctx, createChair,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Thumbnail,
		arg.Price,
		arg.Height,
		arg.Width,
		arg.Depth,
		arg.Color,
		arg.Features,
		arg.Kind,
		arg.Popularity,
		arg.Stock,
	)
	return err
}

const getChair = `-- name: GetChair :one
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair WHERE id = ?
`

func (q *Queries) GetChair(ctx context.Context, id int64) (Chair, error) {
	row := q.db.QueryRowContext(ctx, getChair, id)
	var i Chair
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Height,
		&i.Width,
		&i.Depth,
		&i.Color,
		&i.Features,
		&i.Kind,
		&i.Popularity,
		&i.Stock,
	)
	return i, err
}

const getExistChair = `-- name: GetExistChair :one
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair WHERE id = ? AND stock > 0
`

func (q *Queries) GetExistChair(ctx context.Context, id int64) (Chair, error) {
	row := q.db.QueryRowContext(ctx, getExistChair, id)
	var i Chair
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Height,
		&i.Width,
		&i.Depth,
		&i.Color,
		&i.Features,
		&i.Kind,
		&i.Popularity,
		&i.Stock,
	)
	return i, err
}

const listChairWithPriceCondtion = `-- name: ListChairWithPriceCondtion :many
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair WHERE price >= ? AND price < ? AND stock > 0 ORDER BY popularity DESC, id ASC
`

type ListChairWithPriceCondtionParams struct {
	Price   int32
	Price_2 int32
}

func (q *Queries) ListChairWithPriceCondtion(ctx context.Context, arg ListChairWithPriceCondtionParams) ([]Chair, error) {
	rows, err := q.db.QueryContext(ctx, listChairWithPriceCondtion, arg.Price, arg.Price_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chair
	for rows.Next() {
		var i Chair
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Price,
			&i.Height,
			&i.Width,
			&i.Depth,
			&i.Color,
			&i.Features,
			&i.Kind,
			&i.Popularity,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChairForPurchase = `-- name: UpdateChairForPurchase :exec
UPDATE chair SET stock = stock - 1 WHERE id = ?
`

func (q *Queries) UpdateChairForPurchase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateChairForPurchase, id)
	return err
}
