// Code generated by sqlc. DO NOT EDIT.
// source: chair.sql

package mysql

import (
	"context"
	"database/sql"
)

const createChair = `-- name: CreateChair :exec
INSERT INTO chair(id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateChairParams struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Price       sql.NullInt32
	Height      sql.NullInt32
	Width       sql.NullInt32
	Depth       sql.NullInt32
	Color       sql.NullString
	Features    sql.NullString
	Kind        sql.NullString
	Popularity  int32
	Stock       int32
}

func (q *Queries) CreateChair(ctx context.Context, arg CreateChairParams) error {
	_, err := q.db.ExecContext(ctx, createChair,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Thumbnail,
		arg.Price,
		arg.Height,
		arg.Width,
		arg.Depth,
		arg.Color,
		arg.Features,
		arg.Kind,
		arg.Popularity,
		arg.Stock,
	)
	return err
}

const getChair = `-- name: GetChair :one
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair WHERE id = ?
`

func (q *Queries) GetChair(ctx context.Context, id int64) (Chair, error) {
	row := q.db.QueryRowContext(ctx, getChair, id)
	var i Chair
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Height,
		&i.Width,
		&i.Depth,
		&i.Color,
		&i.Features,
		&i.Kind,
		&i.Popularity,
		&i.Stock,
	)
	return i, err
}

const getExistChair = `-- name: GetExistChair :one
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair WHERE id = ? AND stock > 0
`

func (q *Queries) GetExistChair(ctx context.Context, id int64) (Chair, error) {
	row := q.db.QueryRowContext(ctx, getExistChair, id)
	var i Chair
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Thumbnail,
		&i.Price,
		&i.Height,
		&i.Width,
		&i.Depth,
		&i.Color,
		&i.Features,
		&i.Kind,
		&i.Popularity,
		&i.Stock,
	)
	return i, err
}

const listChairWithCondtion = `-- name: ListChairWithCondtion :many
SELECT id, name, description, thumbnail, price, height, width, depth, color, features, kind, popularity, stock FROM chair
WHERE 
    (price > ? OR ISNULL(?))
AND (price <= ? OR ISNULL(?))
AND (height > ? OR ISNULL(?))
AND (height <= ? OR ISNULL(?))
AND (width > ? OR ISNULL(?))
AND (width <= ? OR ISNULL(?))
AND (width > ? OR ISNULL(?))
AND (width <= ? OR ISNULL(?))
AND (kind = ? OR ISNULL(?))
AND (color = ? OR ISNULL(?))
AND (features = ? OR ISNULL(?))
ORDER BY popularity DESC, id ASC
`

type ListChairWithCondtionParams struct {
	MinPrice1  sql.NullInt32
	MinPrice2  interface{}
	MaxPrice1  sql.NullInt32
	MaxPrice2  interface{}
	MinHeight1 sql.NullInt32
	MinHeight2 interface{}
	MaxHeight1 sql.NullInt32
	MaxHeight2 interface{}
	MinWidth1  sql.NullInt32
	MinWidth2  interface{}
	MaxWidth1  sql.NullInt32
	MaxWidth2  interface{}
	MinDepth1  sql.NullInt32
	MinDepth2  interface{}
	MaxDepth1  sql.NullInt32
	MaxDepth2  interface{}
	Kind1      sql.NullString
	Kind2      interface{}
	Color1     sql.NullString
	Color2     interface{}
	Features1  sql.NullString
	Features2  interface{}
}

func (q *Queries) ListChairWithCondtion(ctx context.Context, arg ListChairWithCondtionParams) ([]Chair, error) {
	rows, err := q.db.QueryContext(ctx, listChairWithCondtion,
		arg.MinPrice1,
		arg.MinPrice2,
		arg.MaxPrice1,
		arg.MaxPrice2,
		arg.MinHeight1,
		arg.MinHeight2,
		arg.MaxHeight1,
		arg.MaxHeight2,
		arg.MinWidth1,
		arg.MinWidth2,
		arg.MaxWidth1,
		arg.MaxWidth2,
		arg.MinDepth1,
		arg.MinDepth2,
		arg.MaxDepth1,
		arg.MaxDepth2,
		arg.Kind1,
		arg.Kind2,
		arg.Color1,
		arg.Color2,
		arg.Features1,
		arg.Features2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chair
	for rows.Next() {
		var i Chair
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Thumbnail,
			&i.Price,
			&i.Height,
			&i.Width,
			&i.Depth,
			&i.Color,
			&i.Features,
			&i.Kind,
			&i.Popularity,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChairForPurchase = `-- name: UpdateChairForPurchase :exec
UPDATE chair SET stock = stock - 1 WHERE id = ?
`

func (q *Queries) UpdateChairForPurchase(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, updateChairForPurchase, id)
	return err
}
