// Code generated by sqlc. DO NOT EDIT.

package mysql

import ()

type Chair struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Price       int32
	Height      int32
	Width       int32
	Depth       int32
	Color       string
	Features    string
	Kind        string
	Popularity  int32
	Stock       int32
}
