// Code generated by sqlc. DO NOT EDIT.

package mysql

import (
	"database/sql"
)

type Chair struct {
	ID          int64
	Name        string
	Description string
	Thumbnail   string
	Price       sql.NullInt32
	Height      sql.NullInt32
	Width       sql.NullInt32
	Depth       sql.NullInt32
	Color       sql.NullString
	Features    sql.NullString
	Kind        sql.NullString
	Popularity  int32
	Stock       int32
}
